export const wave1 = [
    {
        key: 'enemy_2',
        amount: 2,
        yPos: -100,
        stepX: 400,
        stepY: -400,
    },
    {
        key: 'zombie',
        amount: 1,
        xPos: 1400,
        yPos: 500,
        stepX: 0,
        stepY: 0,
    },
    {
        key: 'enemy_2',
        amount: 8,
        xPos: 1400,
        yPos: 100,
        stepX: 130,
        stepY: -80,
    },
    {
        key: 'enemy_1',
        amount: 4,
        yPos: 300,
        stepX: 200,
        stepY: 0,
    }, {
        key: 'enemy_2',
        amount: 4,
        yPos: -100,
        stepX: 80,
        stepY: -40,
    }, {
        key: 'enemy_1',
        amount: 6,
        yPos: 150,
        stepX: 120,
        stepY: 80,
    },
    {
        key: 'zombie',
        amount: 2,
        xPos: 1500,
        yPos: 500,
        stepX: 500,
        stepY: 0,
    },
    {
        key: 'asteroid',
        amount: 1,
        yPos: -100,
        stepX: 120,
        stepY: 80,
    }, {
        key: 'asteroid',
        amount: 1,
        xPos: 900,
        yPos: -100,
        stepX: 120,
        stepY: 80,
    }, {
        key: 'asteroid',
        amount: 1,
        xPos: 1500,
        yPos: -200,
        stepX: 220,
        stepY: 500,
    }, {
        key: 'asteroid',
        amount: 2,
        xPos: 800,
        yPos: -100,
        stepX: 500,
        stepY: -200,
    }, {
        key: 'enemy_1',
        amount: 6,
        yPos: 630,
        stepX: 120,
        stepY: -80,
    },
    {
        key: 'boss_fly',
        amount: 1,
        xPos: 900,
        yPos: 400,
        stepX: 0,
        stepY: 0,
    },
];
